"""
Email sender module for distributing certificates via Gmail SMTP.
Uses Gmail's SMTP server with App Passwords for authentication.
"""

import html
import logging
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr, formatdate
from uuid import uuid4

from config import Config

logger = logging.getLogger(__name__)

# HTML email template
EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }}
        .container {{
            max-width: 600px;
            margin: 40px auto;
            background-color: #ffffff;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 40px;
            text-align: center;
        }}
        .header h1 {{
            color: #ffffff;
            margin: 0;
            font-size: 28px;
            font-weight: 700;
        }}
        .content {{
            padding: 40px;
        }}
        .content h2 {{
            color: #333;
            font-size: 22px;
            margin: 0 0 20px 0;
        }}
        .content p {{
            color: #555;
            line-height: 1.6;
            font-size: 16px;
            margin: 0 0 15px 0;
        }}
        .highlight {{
            background-color: #f8f4ff;
            border-left: 4px solid #667eea;
            padding: 12px 20px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        .highlight p {{
            margin: 5px 0;
        }}
        .btn {{
            display: inline-block;
            padding: 14px 32px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #ffffff;
            text-decoration: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            margin: 20px 0;
        }}
        .footer {{
            background-color: #f9f9f9;
            padding: 20px 40px;
            text-align: center;
            border-top: 1px solid #eee;
        }}
        .footer p {{
            color: #999;
            font-size: 13px;
            margin: 0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎉 Certificate of Achievement</h1>
        </div>
        <div class="content">
            <h2>Congratulations, {name}!</h2>
            <p>We are pleased to present you with this certificate in recognition of your achievement.</p>
            <div class="highlight">
                <p><strong>Recipient:</strong> {name}</p>
                <p><strong>Award:</strong> {prize_position}</p>
                <p><strong>Event:</strong> {event_name}</p>
            </div>
            <p>Your certificate is attached to this email. Please download and save it for your records.</p>
            <p style="text-align: center;">
                <a href="#" class="btn">View Certificate</a>
            </p>
            <p style="color: #888; font-size: 14px; margin-top: 20px;">
                If you have any questions, please contact the event organizers.
            </p>
        </div>
        <div class="footer">
            <p>This certificate was generated by CertiGenius &bull; Automated Certificate Platform</p>
        </div>
    </div>
</body>
</html>
"""


class EmailSender:
    """Handles sending certificate emails via Gmail SMTP with an App Password."""

    def __init__(self, sender_email=None):
        self.server = Config.MAIL_SERVER
        self.port = Config.MAIL_PORT
        self.use_tls = Config.MAIL_USE_TLS
        self.username = Config.MAIL_USERNAME
        self.password = Config.MAIL_PASSWORD
        self.sender = sender_email or Config.MAIL_DEFAULT_SENDER

    def is_configured(self):
        """Check if Gmail SMTP credentials are configured."""
        return bool(self.username and self.password and self.sender)

    def connect(self):
        """Establish a reusable SMTP connection for bulk sending."""
        if not self.is_configured():
            return False, "Not configured"
        try:
            self.server_conn = smtplib.SMTP(self.server, self.port, timeout=30)
            if self.use_tls:
                self.server_conn.ehlo()
                self.server_conn.starttls()
                self.server_conn.ehlo()
            self.server_conn.login(self.username, self.password)
            return True, "Connected"
        except Exception as e:
            logger.error(f"SMTP connect error: {e}")
            self.server_conn = None
            return False, str(e)

    def disconnect(self):
        """Close the reusable SMTP connection."""
        if hasattr(self, "server_conn") and self.server_conn:
            try:
                self.server_conn.quit()
            except Exception:
                pass
            self.server_conn = None

    def send_certificate(
        self, recipient_name, recipient_email, certificate_path,
        prize_position="Participation", event_name=""
    ):
        """
        Send a certificate via Gmail SMTP.

        Args:
            recipient_name: Name of the recipient
            recipient_email: Email address of the recipient
            certificate_path: Path to the certificate PDF file
            prize_position: Prize or position achieved
            event_name: Name of the event

        Returns:
            (success: bool, message: str)
        """
        if not self.is_configured():
            return (
                False,
                "Email sender is not configured. "
                "Set MAIL_USERNAME and MAIL_PASSWORD in .env file. "
                "For Gmail, use an App Password from https://myaccount.google.com/apppasswords",
            )

        try:
            msg = MIMEMultipart("mixed")
            msg["From"] = formataddr(("CertiGenius", self.sender))
            msg["To"] = recipient_email
            msg["Subject"] = f"\U0001f389 Your Certificate - {prize_position}"
            msg["Date"] = formatdate(localtime=True)
            msg["Message-ID"] = f"<{uuid4().hex}@certigenius>"

            # HTML body with escaped dynamic values
            safe_name = html.escape(recipient_name)
            safe_prize = html.escape(prize_position)
            safe_event = html.escape(event_name or "Event")
            html_body = EMAIL_TEMPLATE.format(
                name=safe_name,
                prize_position=safe_prize,
                event_name=safe_event,
            )
            msg.attach(MIMEText(html_body, "html", "utf-8"))

            # Attach certificate PDF
            safe_filename = f"certificate_{recipient_name.replace(' ', '_')}.pdf"
            # Ensure the filename is ASCII-only for maximum compatibility
            safe_filename = safe_filename.encode("ascii", "replace").decode("ascii")
            with open(certificate_path, "rb") as f:
                attachment = MIMEApplication(f.read(), _subtype="pdf")
                attachment.add_header(
                    "Content-Disposition",
                    "attachment",
                    filename=safe_filename,
                )
                msg.attach(attachment)

            # Send using reusable connection if available, otherwise one-off
            if hasattr(self, "server_conn") and self.server_conn:
                self.server_conn.send_message(msg)
            else:
                if self.use_tls:
                    server = smtplib.SMTP(self.server, self.port, timeout=30)
                    server.ehlo()
                    server.starttls()
                    server.ehlo()
                else:
                    server = smtplib.SMTP(self.server, self.port, timeout=30)

                server.login(self.username, self.password)
                server.send_message(msg)
                server.quit()

            logger.info(f"Certificate sent successfully to {recipient_email}")
            return True, "Sent successfully"

        except smtplib.SMTPAuthenticationError:
            error_msg = (
                "Gmail rejected the app password. "
                "Go to https://myaccount.google.com/apppasswords, "
                "generate a new one for 'CertiGenius', and update MAIL_PASSWORD in .env"
            )
            logger.error(error_msg)
            return False, error_msg

        except smtplib.SMTPException as e:
            error_msg = f"SMTP error sending to {recipient_email}: {str(e)}"
            logger.error(error_msg)
            return False, error_msg

        except FileNotFoundError:
            error_msg = f"Certificate file not found: {certificate_path}"
            logger.error(error_msg)
            return False, error_msg

        except Exception as e:
            error_msg = f"Unexpected error sending to {recipient_email}: {str(e)}"
            logger.error(error_msg)
            return False, error_msg
