"""
CertiGenius — Certificate Verification Page
Verify certificates via certificate ID (from QR code or URL).
"""
from sqlalchemy.orm import joinedload

import streamlit as st

from models import Certificate, Base
from utils.db import get_session, init_connection

st.set_page_config(page_title="Verify Certificate — CertiGenius", page_icon="✅", layout="centered")

engine = init_connection()
Base.metadata.create_all(engine)

st.markdown(
    """
    <div style="text-align: center; padding: 1rem 0;">
        <h1 style="font-size: 3rem;">✅</h1>
        <h2 style="color: #212529;">Certificate Verification</h2>
        <p style="color: #6c757d;">Verify the authenticity of a certificate</p>
    </div>
    """,
    unsafe_allow_html=True,
)

# Try to read cert_id from query params (for QR code / deep links)
cert_id_raw = st.query_params.get("cert_id")
cert_id = int(cert_id_raw) if cert_id_raw else None

if not cert_id:
    cert_id = st.number_input(
        "Enter Certificate ID",
        min_value=1,
        step=1,
        help="You can find this on your certificate or in the QR code",
    )
    if not st.button("✅ Verify", type="primary", use_container_width=True):
        st.stop()
elif cert_id:
    if st.button("🔄 Check Another Certificate", use_container_width=True):
        st.query_params.clear()
        st.rerun()

# ---- Lookup ----
session = get_session()
try:
    cert = session.query(Certificate).options(
        joinedload(Certificate.participant),
        joinedload(Certificate.batch),
        joinedload(Certificate.template),
    ).get(cert_id)
finally:
    session.close()

if not cert:
    st.error("❌ Certificate not found. Please check the ID and try again.")
    st.stop()

participant = cert.participant
batch = cert.batch

if not participant or not batch:
    st.error("❌ Certificate data is incomplete.")
    st.stop()

# ---- Success Display ----
st.markdown(
    """
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                border-radius: 16px; padding: 2rem; text-align: center; margin: 1rem 0;
                box-shadow: 0 8px 32px rgba(102, 126, 234, 0.3);">
        <h1 style="font-size: 4rem; margin: 0;">✅</h1>
        <h2 style="color: white; margin: 0.5rem 0;">Certificate Verified</h2>
        <p style="color: rgba(255,255,255,0.8); margin: 0;">This is an authentic certificate</p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown("---")

# Certificate Details
col1, col2 = st.columns(2)

with col1:
    st.markdown("### 📋 Certificate Details")
    st.markdown(f"**Certificate ID:** `#{cert.id}`")
    st.markdown(f"**Status:** {'✅ Valid' if cert.status in ('generated', 'sent') else '❌ Invalid'}")
    st.markdown(f"**Issued:** {cert.created_at.strftime('%B %d, %Y') if cert.created_at else '—'}")
    if cert.sent_at:
        st.markdown(f"**Sent:** {cert.sent_at.strftime('%B %d, %Y') if cert.sent_at else '—'}")

with col2:
    st.markdown("### 🏅 Recipient")
    st.markdown(f"**Name:** {participant.name}")
    st.markdown(f"**Email:** {participant.email}")
    st.markdown(f"**Achievement:** {participant.prize_position}")

st.markdown("---")

# Extra data
extra = participant.get_extra_data()
if extra:
    st.markdown("### 📊 Additional Information")
    for k, v in extra.items():
        if v:
            st.markdown(f"**{k}:** {v}")

# Batch info
st.markdown("---")
st.markdown("### 📦 Batch Information")
st.markdown(f"**Batch:** {batch.name}")
st.markdown(f"**Batch Status:** {batch.status}")
st.markdown(f"**Template:** {cert.template.name if cert.template else '—'}")

# Download link
if cert.file_path:
    import os
    full_path = os.path.join(os.getcwd(), cert.file_path)
    if os.path.exists(full_path):
        with open(full_path, "rb") as f:
            pdf_data = f.read()
        st.download_button(
            label="📄 Download Certificate PDF",
            data=pdf_data,
            file_name=f"certificate_{participant.name.replace(' ', '_')}.pdf",
            mime="application/pdf",
            use_container_width=True,
            type="primary",
        )

st.markdown("---")
st.markdown(
    """
    <div style="text-align: center; color: #adb5bd; font-size: 0.85rem;">
        <p>This certificate was generated by <strong>CertiGenius</strong> — Automated Certificate Platform</p>
    </div>
    """,
    unsafe_allow_html=True,
)
